event_scheduling_site/SCM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from scmapp import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'^$',views.index,name='index'),
    path('scm/',include('scmapp.urls')),
    path('admin/', admin.site.urls),
    path('', include('scmapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event_scheduling_site/scmapp/urls.py
from django.urls import include, re_path
from scmapp import views

app_name = 'scmapp'

urlpatterns = [

    re_path(r'^$',views.index,name='admin_home'),
    re_path(r'^admin_event',views.admin_event,name='admin_event'),

    re_path(r'^update_event/(?P<id>\d+)/$',views.update_event,name='update_event'),
    re_path(r'^db_update_event/(?P<id>\d+)/$',views.db_update_event,name='db_update_event'),
    re_path(r'^db_delete_event/(?P<id>\d+)/$',views.db_delete_event,name='db_delete_event'),

    re_path(r'^add_event',views.add_event,name='add_event'),
    re_path(r'^db_add_event',views.db_add_event,name='db_add_event'),

    
]

event_scheduling_site/scmapp/models.py
from django.db import models
import datetime
import os


def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('uploads/', filename)

class Event(models.Model):
    eid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    date = models.DateField()
    time = models.TimeField()
    duration = models.IntegerField()
    image = models.ImageField(upload_to=filepath, null=True, blank=True)



event_scheduling_site/scmapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from scmapp.models import Event
import os

# Create your views here.

def index(request):
    return render(request,'admin_home.html')


#Admin Manage Event Page
def admin_event(request):
    event = Event.objects.all()
    data = {'event':event}

    if 'event_status' in request.session:
        data['status'] = request.session.get('event_status')

    return render(request,'admin_event.html',context=data)

#Admin Update Event Page
def update_event(request,id):
    event = Event.objects.get(eid=id)
    event.date = event.date.strftime('%Y-%m-%d')
    event.time = event.time.strftime('%H:%M:%S')
    data = {'event':event}
    return render(request,'update_event.html',context=data)

#Admin Add Event Page
def add_event(request):
    return render(request,'add_event.html')

#BACKEND -> For Update Event
def db_update_event(request,id):
    if request.method == 'POST':
        event = Event.objects.get(eid=id)
        event.name = request.POST.get('name')
        event.date = request.POST.get('date')
        event.time = request.POST.get('time')
        event.duration = request.POST.get('duration')
        if len(request.FILES) != 0:
            if len(event.image)>0:
                os.remove(event.image.path)
            event.image = request.FILES['image']
        event.save()

        request.session['event_status'] = 'Event updated successfuly'
        return admin_event(request)
    context = {'event':event}
    return render(request,'admin_event.html',context)

#BACKEND -> For Delete Events
def db_delete_event(request,id):
    if request.method == 'GET':
        event = Event.objects.get(eid=id)
        event.delete()

        request.session['event_status'] = 'Event deleted successfuly'
        return admin_event(request)
    else:
        return HttpResponse("Something went wrong!!!!!")

#BACKEND -> For Add Event
def db_add_event(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        date = request.POST.get('date')
        time = request.POST.get('time')
        duration = request.POST.get('duration')
        if len(request.FILES) != 0:
            image = request.FILES['image']

        event = Event(name=name,date=date,time=time,duration=duration,image=image)
        event.save()
        request.session['event_status'] = 'Event added successfuly'
        return admin_event(request)
    else:
        return HttpResponse("Something went wrong!!!!!")

event_scheduling_site/templates/add_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Create Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid header text-center bg-danger">
<h1 style="color: white">Event Details</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-danger">
     <center><h1 style="color: rgb(0, 0, 0); background-color: rgb(206, 31, 60); margin-right: 30px;"> Create Event</h1></center>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_add_event' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              Name of event<br>
              <input type="text" name="name" autocomplete="off" required><br>

              Date<br>
              <input type="date" name="date" autocomplete="off" required><br>

              Time<br>
              <input type="time" name="time" required>

              Duration(hours)<br>
              <input type="number" name="duration" autocomplete="off" required><br>

              Upload brochure<br>
              <input type="file" name="image">

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Create" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:admin_event' %}" class="btn btn-primary" style="color: white;">Back</a>
    </div>
  </div>
</div>
</body>
</html>

event_scheduling_site/templates/admin_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Events</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/admin_event.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid header text-center">
  <h1 class="bg-danger" style="color: white;">Manage Events</h1>
</div>

<div class="container box bg-success">
  <a href="add_event.php"><button style="float:right;">Create Event</button></a>
  <h1 style="color: white;">Event Details<h1></h1><br>
  
  <span style="font-size:16px;">{{ status }}</span>

  <table>
    <tr class="bg-primary" style="color: white;">
      <td>No</td>
      <td>Event name</td>
      <td>Date</td>
      <td>Time</td>
      <td>Duration</td>
      <td>Brochure</td>
      <td>Update</td>
      <td>Delete</td>
    </tr>

    {% for e in event %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ e.name}}</td>
        <td>{{ e.date }}</td>
        <td>{{ e.time }}</td>
        <td>{{ e.duration }}</td>        
        {% if e.image %}
        <td>
          <a href="{{e.image.url}}" target="_blank">
          <img src = "{{e.image.url}}" alt="">
          </a>        
        </td>
        {% else %}
        <td>
          <a href="{% static 'res/event.jpeg'%}" target="_blank">
          <img src = "{% static 'res/event.jpeg'%}" alt="">
        </a>
        </td> 
        {% endif %}      
        <td><a href="{% url 'scmapp:update_event' id=e.eid %}">Update</a></td>
        <td><a href="{% url 'scmapp:db_delete_event' id=e.eid %}">Delete</a></td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="7" align="center">No Events</td>
      </tr>
    {% endfor %}

  </table>

  <div class="footer">
    <a href="{% url 'scmapp:admin_home' %}"><button>Back</button></a>
  </div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

event_scheduling_site/templates/admin_home.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Events Management System</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body class="bg-primary" style="color:white">
<div class="container-fluid header text-center bg-danger">
 <h1>Wow Events Happening</h1>
</div>

<div class="container" align="center">
  <div>
    <a href="{% url 'scmapp:admin_event' %}">
    <div class="card bg-danger">
      <img src="{% static 'res/event.jpg' %}">
      <div class="card-title text-center" style="color: white;">Events</div>
    </div>
    </a>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

event_scheduling_site/templates/update_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Update Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body class="bg-success">
<div class="container-fluid header text-center">
  <h1 class="bg-primary" style="color: white;">Manage Event</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-danger">
      <center><h1 class="bg-success" style="color: white; margin-right: 30px;">Update Event</h1></center>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'scmapp:db_update_event' id=event.eid %}" method="post">
              {% csrf_token %}
              Name of event<br>
              <input type="text" name="name" autocomplete="off" value="{{ event.name }}" required><br>

              Date<br>
              <input type="date" name="date" autocomplete="off" value="{{ event.date }}" required><br>

              Time<br>
              <input type="time" name="time" value="{{ event.time }}" min="06:00" max="18:00" required><br>

              Duration(hours)<br>
              <input type="number" name="duration" autocomplete="off" value="{{ event.duration }}" min="1" required><br>

              Brochure<br>
              {% if event.image %}
                <img src = "{{event.image.url}}" alt="image here" width="100" height="100" target="_blank">
              {% endif %}      
              <input type="file" name="image" >

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Update" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'scmapp:admin_event' %}" class="btn btn-primary">Back</a>
    </div>
  </div>
</div>

</body>
</html>